name: Semantic Pull Request

on:
    pull_request:
        types:
            - edited
            - opened
            - synchronize
    push:
        branches:
            - gh-readonly-queue/main/**

jobs:
    validate-title:
        name: Validate Title
        runs-on: ubuntu-latest

        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        timeout-minutes: 5
        steps:
            - name: Validate pull request title
              uses: amannn/action-semantic-pull-request@e7d011b07ef37e089bea6539210f6a0d360d8af9
              with:
                  validateSingleCommit: true